depot/config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :line_items do
    member do
      patch :reduce
    end
  end

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

end

depot/app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	has_many :orders, through: :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	validates :title, :description, :image_url, presence: true
	validates :price, numericality: { greater_than_or_equal_to: 0.01 }
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
		message: 'must be an URL for GIF, JPG or PNG image.'
	}

	def self.latest
		Product.order(:updated_at).last
	end

	private

	# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end
	end
	
end

depot/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    # Permite fazer upload de imagens direto na pasta app/assets/images
    if uploaded_io = params[:product][:picture]
      File.open(Rails.root.join('app', 'assets', 'images', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end

      @product.image_url = uploaded_io.original_filename
    end

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    # Permite fazer upload de imagens direto na pasta app/assets/images
    if uploaded_io = params[:product][:picture]
      File.open(Rails.root.join('app', 'assets', 'images', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end

      File.delete(Rails.root.join('app', 'assets', 'images', @product.image_url)) if File.exist?(Rails.root.join('app', 'assets', 'images', @product.image_url))

      @product.image_url = uploaded_io.original_filename
    end

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    # Apaga a imagem antes de destruir o produto
    File.delete(Rails.root.join('app', 'assets', 'images', @product.image_url)) if File.exist?(Rails.root.join('app', 'assets', 'images', @product.image_url))

    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

depot/app/helpers/products_helper.rb
module ProductsHelper
end

depot/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "erro") %> impediram que o produto fosse salvo:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, "Description" %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :picture, "Image" %><br>
    <%= f.file_field :picture, required: true %>
  </div>
  <div class="field">
    <%= f.label :price, "Price" %><br>
    <%= f.text_field :price %>
  </div>
  <hr/>
  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-success" %>
  </div>
<% end %>

depot/app/views/products/_product.html.erb
<div class="entry">
	<%= link_to product, title: product.title do %>
		<p class="text-center title"><%= truncate(product.title, length: 25) %></p>
	<% end %>

	<%= image_tag(product.image_url, class: "center-block") %>

	<p class="price text-center"><%= number_to_currency(product.price) %></p>

	<%= button_to 'Add to cart', line_items_path(product_id: product), class: "btn btn-success center-block", remote: true %>
</div>

depot/app/views/products/edit.html.erb
<h2>Editing product</h2>

<br/>

<%= render 'form' %>

<%= link_to 'Show', @product, class: "btn btn-primary" %>
<%= link_to 'Back', products_path, class: "btn btn-default" %>

depot/app/views/products/index.html.erb
<h2>Listing products</h2>

<br/>

<table class="table table-striped">
  <% @products.each do |product| %>
    <tr>
      <td class="list_image">
        <%= image_tag(product.image_url) %>
      </td>

      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
        </dl>
      </td>

      <td class="list_actions">
        <%= link_to 'Show', product, class: "btn btn-xs btn-primary" %>
        <%= link_to 'Edit', edit_product_path(product), class: "btn btn-xs btn-info" %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
      </td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Product', new_product_path, class: "btn btn-success" %>

depot/app/views/products/new.html.erb
<h2>New product</h2>

<br/>

<%= render 'form' %>

<%= link_to 'Back', products_path, class: "btn btn-default" %>

depot/app/views/products/show.html.erb
<h2><%= @product.title %></h2>

<br/>

<%= image_tag(@product.image_url, class: 'list_image') %>

<hr/>

<p>
	<%= strip_tags(@product.description) %>
</p>

<p>
  <b>
  	Price: <%= number_to_currency(@product.price) %>
  </b>
</p>