depot/config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :line_items do
    member do
      patch :reduce
    end
  end

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

end

depot/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
		product.price * quantity
	end
end

depot/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create, :update, :destroy, :reduce]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy, :reduce]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    #@line_item = LineItem.new(line_item_params)
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
        format.js
        #format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    @line_item.quantity += 1

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @cart, notice: 'Product successfully added to cart.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to @cart, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reduce
    @line_item.quantity -= 1

    respond_to do |format|
      if @line_item.save
        @line_item.destroy if @line_item.quantity == 0
        format.html { redirect_to @cart, notice: 'Product successfully removed from cart.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

depot/app/helpers/line_items_helper.rb
module LineItemsHelper
end

depot/app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

depot/app/views/line_items/_line_item.html.erb
<tr>
	<td><%= line_item.quantity %>&times;</td>
	<td><%= line_item.product.title %></td>
	<td><%= number_to_currency(line_item.total_price) %></td>
	<td class="text-center table-add-more"><%= button_to '+', line_item_path(line_item), method: 'patch', class: "btn btn-xs btn-success" %></td>
	<td class="text-center table-add-more"><%= button_to '-', reduce_line_item_path(line_item), method: 'patch', class: "btn btn-xs btn-warning" %></td>
	<td class="text-center table-add-more"><%= button_to 'x', line_item_path(line_item), method: 'delete', class: "btn btn-xs btn-danger" %></td>
</tr>

depot/app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s", line_item.quantity, truncate(line_item.product.title, length: 50)) %>

depot/app/views/line_items/_line_item_mail.html.erb
<tr>
	<td><%= line_item.quantity %>&times;</td>
	<td><%= line_item.product.title %></td>
	<td><%= number_to_currency(line_item.total_price) %></td>
</tr>

depot/app/views/line_items/create.js.erb
$("span#cart-info").html("<%= cart_info(@cart).to_s %>");

$('li#cart-link').css({'background-color':'#F0E68C'}).animate({'background-color':'#226'}, 1000);

depot/app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

depot/app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

depot/app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

depot/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>